### PR TITLE
Fix CMD_RESTART with relative paths as argv[0].

### PR DESCRIPTION
**Pull request by jcjordyn130**

### CODE REVIEW

**Comment by SaberUK** [comment]
Thanks for the patch!

On what platforms and configurations (i.e. home directory, system-wide, etc) have you tested this?

**Comment by jcjordyn130** [comment]
You're welcome for the patch, I've tested it on Void Linux (x86_64, glibc) with an in-tree install.

**Comment by SaberUK** [comment]
Merged, thanks again! 👍

**Comment by jcjordyn130** [comment]
You're welcome again 👍

**Pull request merged**
