### PR TITLE
m_sasl: send host/ip info

### PR DESCRIPTION
**Pull request by Adam-**

### CODE REVIEW

**Comment by attilamolnar** [comment]
Is this confirmed to not break any anope and atheme versions which are currently working with inspircd?

**Comment by Adam-** [comment]
Anope supports this fine.

**Comment by attilamolnar** [comment]
Ok, I need a confirmation that this works on atheme too before merging

**Comment by Robby-** [comment]
I've been testing this with Anope and this works fine for regular IRC clients. However, I also use m_cgiirc because I'm running a KiwiIRC-based webchat. When a webchat user connects, the IRCd will send the address of the webserver the webchat is running on, instead of sending the host/IP address provided in WEBIRC (which is the very first thing KiwiIRC sends).

**Comment by grawity** [comment]
@attilamolnar Atheme has supported this since 7.2.7; older versions will just ignore it as an unrecognized subcommand.

**Comment by Robby-** [comment]
This reminds me I needed to poke @attilamolnar as well, regarding the bug with m_cgiirc when using this PR, which I forgot, so here we go.

**Comment by attilamolnar** [comment]
@Adam- can you check the issue mentioned by @Robby-?

**Comment by Adam-** [comment]
@attilamolnar done.

**Comment by Robby-** [comment]
I have been running the updated PR for about 24 hours now and can confirm this has fixed the issue. Thanks @Adam-.

**Comment by attilamolnar** [comment]
Thanks!

**Pull request merged**
