### PR TITLE
set LDAP_OPT_REFERRALS option as LDAP_OPT_OFF.

### PR DESCRIPTION
**Pull request by takano32**
Some of LDAP servers return 'Search failed' w/ LDAP_OPT_REFERRALS is LDAP_OPT_ON.
And many LDAP clients are also disabling follow referrals option.

I wanna set off this option also in InspIRCd.

Thank you.

### CODE REVIEW

**Comment by takano32** [comment]
Excuse me... :bow:

Could you set the milestone to v2.0.x?
or
Please tell me the reason of this feature is to set the milestone v.2.2.x.

@attilamolnar , @ChrisTX

**Comment by attilamolnar** [comment]
@takano32 This is milestone 2.2 because the 2.0 branch is bugfix-only.

**Comment by takano32** [comment]
@attilamolnar Thanks. I'm looking forward to 2.2. :hamster:

**Comment by SaberUK** [comment]
I have done extensive searches about this LDAP option and I can't seem to find any cases where disabling referrals fixed anything. In fact, all of the cases I found were people who fixed their LDAP setups by *enabling* it.

Additionally I searched for "JIRA follow referrals" as mentioned previously I could only find an issue where support in JIRA was requested but denied by the developers.

Please contact whoever runs your LDAP server and ask them to fix it instead.

**Pull request closed without merging**
