### PR TITLE
Various changes mainly relating to the build system.

### PR DESCRIPTION
**Pull request by SaberUK**
ec971cb72c3e9b1f1646a4c76ba1ddaf7c7221e5 will probably break Jenkins.

@tobgen can you change the Jenkinses to pass `--development` to configure?

### CODE REVIEW

**Comment by md-5** [comment]
Seriously seems like using a off the shelf buildsystem is worth considering given how often this one changes

**Comment by SaberUK** [comment]
Even if you used CMake or some other build system we would still need to change it to add features like this.

**Comment by md-5** [comment]
@SaberUK why can't they? http://www.cmake.org/download/

**Comment by SaberUK** [comment]
Good luck explaining how to install CMake to someone who has problems typing `./configure` and `make install`. Also, CMake doesn't offer an interactive configuration system so we would have to maintain the existing one as a wrapper for CMake.

Besides, i'm fine with maintaining the build system.

**Comment by Zayelion** [comment]
Developer vs user mindset. Why most people dont use Linux, and there are installers for most things. Build system 'just makes it work'.

**Comment by attilamolnar** [comment]
> Seriously seems like using a off the shelf buildsystem is worth considering given how often this one changes

The reason why inspircd has its own build system is historical. If the project was started today it would have more dependencies and less custom code in general for sure.

However:

> Even if we used CMake or some other build system we would still need to change it to add features like this.

CMake does not work magically either and has its own problems. @SaberUK is naturally more familiar with their own code than any other build system, and since they're the one who does the lion's share of work on the build system (even if we had another one) ultimately it's their choice.

@SaberUK Thanks!

**Pull request merged**
