### PR TITLE
Undocument <power> and set the default to the server name.

### PR DESCRIPTION
**Pull request by SaberUK**
We could alternately make it an oper priv to die without the password. What do you think @attilamolnar?

### CODE REVIEW

**Comment by attilamolnar** [comment]
I think this is fine the way it is. These commands can be disabled currently by not allowing any oper to use them (`<class:commands>`). The password nowadays is a failsafe mechanism so opers who do have access to these commands won't accidently stop the server. Having no password simply removes this failsafe mechanism for those who don't like it.

**Comment by Adam-** [comment]
Many other ircds use /die server.name with an oper priv, which I think is what this should do.

**Comment by SaberUK** [comment]
@attilamolnar As is you can't just use /DIE without a password. You have to explicitly specify a blank password parameter (i.e. `DIE :`). If we are going to make it intentional that opers can use /DIE without a password then we should make it so the parameter is optional.

**Comment by attilamolnar** [comment]
What do you think of removing `<power>` from the 3.0 example config and passing the local server name as the default value to `getString()`? This way `<power>` blocks in 2.0 configs will behave as in 2.0 and 3.0 will have the behavior @Adam- said.

**Comment by SaberUK** [comment]
@attilamolnar I can do that yeah.

**Comment by attilamolnar** [comment]
:+1:

**Comment by SaberUK** [comment]
@attilamolnar Like this?

**Comment by attilamolnar** [comment]
Please update the helpop text as well.

**Comment by SaberUK** [comment]
@attilamolnar Done!

**Comment by attilamolnar** [comment]
Thanks!

**Pull request merged**
