### PR TITLE
Strip carriage returns in the config parser.

### PR DESCRIPTION
**Pull request by SaberUK**

### CODE REVIEW

**Comment by attilamolnar** [comment]
I don't know if this is the best solution because \r\n will turn into two spaces which might be undesirable. What do you think?

**Comment by SaberUK** [comment]
@attilamolnar I don't think its too much of a problem but I could change it to not do that if you think it is.

**Comment by SaberUK** [comment]
@attilamolnar I have updated the parser to skip carriage returns which should solve this in a more elegant way.

**Comment by attilamolnar** [comment]
Thanks!

**Pull request merged**
