### PR TITLE
m_sasl.cpp: fix description

### PR DESCRIPTION
**Pull request by Mikaela**

### CODE REVIEW

**Comment by attilamolnar** [comment]
Hello! Why are you shortening "IRC Authentication Layer" to IAL? I'm ok with the other change, sasl is no longer specific to atheme, we changed this in the config as well for the same reason.

**Comment by Mikaela** [comment]
```
[13:52:29] <Mikaela> [13:48:24] 9* m_sasl.so Provides support for IRC Authentication Layer (aka: atheme SASL) via AUTHENTICATE.
[13:52:29] <Mikaela> I have never heard IAL being called as "atheme SASL", usually just SASL
[14:11:34] <SaberUK> Mikaela: patches accepted
[14:12:30] <Mikaela> too lazy even if I found the file and I wouldn't be sure what to write there instead
[14:12:35] <kaniini> really it should just be called IAL
[14:12:41] <kaniini> IAL is the binding
[14:13:16] <kaniini> and also technically encompasses other things like accounts, etc.
[14:13:29] <Mikaela> and those branches are confusing
[14:15:20] <SaberUK> Mikaela: what branches
[14:15:34] <Mikaela> https://github.com/inspircd/inspircd/branches
[14:15:46] <Mikaela> if I was to fix it, which branch would I put it into
[14:15:47] <SaberUK> insp20 is 2.0, master is 2.2
[14:15:55] <SaberUK> its a documentation fix so.. probably 2.0?
[14:16:59] <commits> Mikaela forked inspircd to Mikaela/inspircd http://git.io/pbV6
[14:17:23] <Mikaela> /* $ModDesc: Provides support for IAL (aka: SASL) via AUTHENTICATE. */
[14:17:23] <Mikaela> ?
[14:19:02] <SaberUK> no, the Version attribute
[14:19:07] <SaberUK> in GetVersion
[14:19:15] <SaberUK> those ModDesc's do nothing, i removed them in master
[14:19:33] <Mikaela> ModDesc is the only part where I see atheme sasl in that file
[14:20:51] <Googolplexed> Right near the bottom, GetVersion()
[14:21:52] <Mikaela> oh, found it
[14:22:04] <Mikaela> is that otherwise correct?
[14:29:09] <Mikaela> kaniini?
[14:29:32] <Mikaela> "Provides support for IAL (aka: SASL) via AUTHENTICATE."
[14:29:39] <kaniini> Mikaela: yes, seems reasonable,
[14:29:54] <commits> Mikaela opened PR inspircd/#1011 (m_sasl.cpp: fix description) insp20...patch-1 http://git.io/pb6m - 
```

**Comment by attilamolnar** [comment]
Please change IAL back to what it was, we are trying to make it more clear not less clear.

**Comment by Mikaela** [comment]
Is this what you mean?

**Comment by kaniini** [comment]
yes

**Comment by attilamolnar** [comment]
> Is this what you mean?

No, I want no IAL, i.e. `Provides support for IRC Authentication Layer, aka SASL`.

**Comment by attilamolnar** [comment]
Fixed, closing.

**Pull request closed without merging**
