### PR TITLE
Remove non-existant extban M: from docs

### PR DESCRIPTION
**Pull request by Renegade334**

### CODE REVIEW

**Comment by SaberUK** [comment]
This should be filed against the `insp20` branch. If you want I can add it to #991 though.

**Comment by Renegade334** [comment]
Let me know how best you'd like to handle it. Feel free to cherry-pick the commit into `insp20` if that's easiest.

**Comment by attilamolnar** [comment]
@Renegade334 Please send a PR targetting insp20, because this is an issue with the documentation that applies to 2.0 as well. If you don't want to then I'll cherry-pick this later.

**Comment by Renegade334** [comment]
Shall do!

**Pull request closed without merging**
