### PR TITLE
Add option to make a connect block not match users with an account

### PR DESCRIPTION
**Pull request by linuxdaemon**
Allows setting a connect class which will only match a user who has not
logged in

### CODE REVIEW

**Comment by SISheogorath** [comment]
Can find a better way to do that? Somehow I already see people putting both options into one connect class wondering why their connects fail. There should be at least some debug logging details and, as mentioned before, maybe we can find a better way to put it.

How about a config called accountpolicy? Which then can be: `required`, `ignored` and `forbidden` with `ignored` as default?

**Comment by linuxdaemon** [comment]
That's a decent idea, just didn't want to break compat with 2.0 in this case. If @SaberUK is fine with losing that compat, then I'll definitely implement it, it'll be a lot easier to deal with.

**Comment by linuxdaemon** [comment]
As suggested by @Robby- the current idea is `<account account="deny/allow/require">` for only match no account, allow any state, require account respectively. Unless anyone has any objections, I may go ahead and update this PR to use that.

With respect to the old syntax though, I think leaving the handling in for it should be fine

**Comment by linuxdaemon** [comment]
I think this now fits the currently agreed terminology from the discussion on IRC. @Robby- thoughts?

**Comment by Robby-** [comment]
@linuxdaemon: I don't really have anything else to add, LGTM

**Comment by linuxdaemon** [comment]
Anything holding this one up @SaberUK ? I've had a few people express interest in it for 3.0 (and a backport for 2.0 I'll do in contrib)

**Comment by linuxdaemon** [comment]
@SadieCat Any movement on this? it came up again, it's very useful for making it so SASL users can bypass dnsbl checks

**Pull request closed without merging**
