### PR TITLE
Tell git to store .bat files as CRLF

### PR DESCRIPTION
**Pull request by docwhat**
You can also add additional types, such as:

```
*.cpp  text diff=cpp eol=lf
*.h    text diff=cpp eol=lf
```

Ciao!

### CODE REVIEW

**Comment by attilamolnar** [comment]
Why is this necessary? Can't Windows execute the .bat file as it is currently?

**Comment by docwhat** [comment]
Sure. But why not use the right line endings? That would let someone open the file in notepad on Windows.

**Comment by SaberUK** [comment]
You probably shouldn't be using notepad for editing code files.

**Comment by docwhat** [comment]
I was thinking just to view it.

**Comment by attilamolnar** [comment]
Thanks!

**Pull request merged**
