### PR TITLE
Fix the default xline.db path in modules.conf.example.

### PR DESCRIPTION
**Pull request by SaberUK**

### CODE REVIEW

**Comment by SaberUK** [comment]
I have removed "Make implementing XLine::Matches(User*) optional." from this PR as it seems like it triggers a bug in some older GCCs for some reason.

**Comment by attilamolnar** [comment]
The existing xline code needs to go, at this point it's pointless to do code quality improvements such as deduplication or simplification on it. The xline.db path fix is fine and I'd like to merge that.

**Comment by SaberUK** [comment]
@attilamolnar Are you planning to rewrite it for 3.0 then?

**Comment by attilamolnar** [comment]
@SaberUK Yes.

**Comment by SaberUK** [comment]
@attilamolnar Done.

**Comment by attilamolnar** [comment]
Thanks!

**Pull request merged**
