### PR TITLE
Add configuration for building with Travis-CI.

### PR DESCRIPTION
**Pull request by SaberUK**
`travis-ci.sh` is only needed for insp20. On master the script can just use "./tools/test-build $CXX".

### CODE REVIEW

**Comment by SaberUK** [comment]
I can make this build modules too but i'm not sure which modules should be built. Opinions?

**Comment by Sheogorath-SI** [comment]
I would say SSL/TLS modules, may m_geoip, all defaults and the regex modules.

Because those are the most widely used modules.

I would say SSL/TLS is a must openssl and gnutls.

**Comment by SaberUK** [comment]
I've made it build all of the modules apart from m_regex_stdlib (which requires a C++11 compiler which I don't think Travis has without installing it manually) and m_mssql (which is completely broken, see #1154).

**Comment by Sheogorath-SI** [comment]
To upgrade and use the all libs you can provide [travis_wait](https://docs.travis-ci.com/user/common-build-problems/) as prefix for the update command. I would also extract the dependencies from the build script.

May separate file for debian dependencies in a external script which can called by the build script but also by no name users to install dependencies for modules. Would be helpful for support.

**Comment by SaberUK** [comment]
>To upgrade and use the all libs you can provide travis_wait as prefix for the update command.

We can't because thats only for things that don't provide output. We are apparently exceeding the time a Travis build can take overall.

>May separate file for debian dependencies in a external script which can called by the build script but also by no name users to install dependencies for modules. Would be helpful for support.

Some of the package names are different on different versions of Ubuntu so that wouldn't be very useful. I do have plans to integrate this into the build system (i.e. `./modulemanager install-dep ssl_gnutls`) in master once everything else is done though.

**Comment by attilamolnar** [comment]
Thanks!

**Pull request merged**
