### PR TITLE
Added missing Snomask

### PR DESCRIPTION
**Pull request by Gavin-X**

### CODE REVIEW

**Comment by SaberUK** [comment]
Is this missing in 2.0 as well as 3.0?

If so, can you retarget your PR to be against the insp20 branch?

Thanks!

**Comment by Robby-** [comment]
I've checked `m_override.cpp´ and there is no capital `V` snomask. The fact that you can set `V` on yourself doesn't mean it exists and does anything.

**Comment by Heufneutje** [comment]
You might want to rebase your branch.

**Comment by Robby-** [comment]
@Heufneutje No, he should just close this PR instead. There is no capital `V` snomask.

**Comment by attilamolnar** [comment]
@Gavin-X Please rebase your commit on top of the insp20 branch. Currently this PR is trying to merge the master branch into the insp20 branch.

**Pull request closed without merging**
