### PR TITLE
Allows changing nick specifying password

### PR DESCRIPTION
**Pull request by iwalkalone69**
This allows to change nick specifying password (ircu style).

NICK nick:password

or

NICK nick!password

### CODE REVIEW

**Comment by SaberUK** [comment]
This should be in its own module rather than in a core module and should probably be filed against inspircd-extras for 2.0.

**Comment by SISheogorath** [comment]
And to be honest, why `NICK <nickname>!<password>|<nickname>:<password>` this really makes no sense. Even channels split up passwords and you can't have more than one nick.

So `NICK <nickname> [:]<password>` would be less weird and work with the existing parsers.

**Comment by iwalkalone69** [comment]
Thanks.

I will change it according your comments.

**Comment by iwalkalone69** [comment]
@SaberUK, after reviewing, I see that to deliver it to an external module is not possible because in line **58** of **src/coremods/core_user/cmd_nick.cpp** nick syntax is checked:

`else if (!ServerInstance->IsNick(newnick))`

And the OnUserPreNick is after that, in line 65:

`FIRST_MOD_RESULT(OnUserPreNick, MOD_RESULT, (user, newnick));`

The solution I can see consist in putting OnUserPreNick before nick check and move the code introduced before to an external module.

Am I right?

Thanks.

**Comment by genius3000** [comment]
You can use OnPreCommand to catch it (and strip the password) before the NICK command handler runs.

**Comment by iwalkalone69** [comment]
Thanks @genius3000! It worked for me.

I remove the PR as no changes are needed.

**Pull request closed without merging**
