### PR TITLE
Replace snprintf usage with InspIRCd::Format.

### PR DESCRIPTION
**Pull request by SaberUK**
Now all formatting code goes through InspIRCd::Format and doesn't mess around with C arrays.

### CODE REVIEW

**Comment by SaberUK** [comment]
This also inadvertently fixes a build error on Windows reported by MY123 in #inspircd.

**Comment by attilamolnar** [comment]
For now please only switch core_stats to `InspIRCd::Format()` because the function returns a `std::string` causing extra memory allocation/deallocation that doesn't happen with plain `snprintf`. This doesn't affect core_stats but does affect every other call site modified by this PR, those don't need the `std::string`. If we add a new `Format()` function that returns a `const char*` then the rest of the code can be switched (and the `#define` in inspircd_win32wrapper.h can be dropped).

**Comment by SaberUK** [comment]
@attilamolnar I reverted some of the changes but I don't think the cloaking and map changes are allocating any more memory than they would have previously.

**Comment by attilamolnar** [comment]
All calls to `Format()` cause a temporary string to be created even if that string is appended to another string immediately, but we do get simpler code. Either way, a new `Format()` function I mentioned in the previous comment will get rid of the temporary strings in those cases.

**Comment by attilamolnar** [comment]
Thanks!

**Pull request merged**
