### PR TITLE
Some updates to INFO.

### PR DESCRIPTION
**Pull request by rburchell**
Simple changes to bring things up to date with today's reality.

### CODE REVIEW

**Comment by attilamolnar** [comment]
Probably the [messages on boot](https://github.com/inspircd/inspircd/blob/master/src/inspircd.cpp#L371) should be updated as well if you agree.

**Comment by rburchell** [comment]
Ah, damn, I remember forgetting to change those in the past too I'm sure. Maybe we should just remove the list and add a "For info on authors & contributors, see /INFO"?

**Comment by attilamolnar** [comment]
OK, I'll merge when you're done with that.

**Comment by rburchell** [comment]
Done (and rebased, for good measure).

Sorry for the delay.

**Comment by attilamolnar** [comment]
Thanks!

**Pull request merged**
